### ISSUE TITLE
apply dagcoin styles to explorer.

### ISSUE THREAD

**Issue by fishera123** [dagcoin/explorer#1]
also amounts should be in dags not in micro-dags

**Comment by irinadoros** [comment]
* transaction spot should be blue - NOK
* if user clicks on amount, then it turns into zero "0" - NOK
<img width="855" alt="exploreramountsdevnet" src="https://user-images.githubusercontent.com/35455231/39183527-f7b4252a-47c8-11e8-9982-c93827fa632b.png">

**Comment by irinadoros** [comment]
* transaction spot should be blue - OK
* if user clicks on amount, then it stay same - OK
* amounts issue is still exist - NOK

**Comment by irinadoros** [comment]
* amounts are same in the explorer and in the wallet - OK

**Comment by irinadoros** [comment]
![image](https://user-images.githubusercontent.com/35455231/39246090-3bc5dee0-489e-11e8-9c56-628958172ac6.png)

**Comment by irinadoros** [comment]
Amounts presented in explorer in dags not in micro-dags - OK
